### ISSUE TITLE
MSSQL/PostgreSQL data builder

### ISSUE THREAD

**Issue by sibartlett** [mj1856/GeoTimeZone#13]
We currently use NTS for all of our geospatial calculations. There is a small issue though, because NTS only handles calculations based on a Euclidean plane.

The Earth is a spheroid, and because of that, we should ideally be using a WGS-84 projection.

Unfortunately, there are no libraries that support the spatial calculations we require on a WGS-84 projection... so we would have to use the spatial support in either MSSQL or PostgreSQL.

**Comment by mj1856** [comment]
Closing this, as I'm satisfied with the current approach.
