### ISSUE TITLE
Update tz_world data

### ISSUE THREAD

**Issue by sibartlett** [mj1856/GeoTimeZone#17]
The data should be updated and the disclaimer removed from the README.

The source data (tz_world) has been updated to tzdb 2015g.

**Comment by mj1856** [comment]
Hi Simon!  :)

Yes, I plan to update, but I was hoping Eric would address the Dawson Creek border first.  See the tz list.

**Comment by mj1856** [comment]
I went ahead and updated it.  Pushed to NuGet as version 1.1.0.

If Eric updates for the Dawson Creek border, I'll push a 1.1.1 version.
