### ISSUE TITLE
Timezone misplaced to South Africa instead of Europe Estonia

### ISSUE THREAD

**Issue by KristjanLaane** [mj1856/GeoTimeZone#19]
This test fails:

```
[Test]
public void TimeZoneFromCoordinates()
{
    double latitude = 59.470977;
    double longitude = 24.708448;                        
    string timeZoneId = TimeZoneLookup.GetTimeZone(latitude, longitude).Result;
    Assert.True(timeZoneId.Equals("Europe/Tallinn"), "{0}, {1} Is Europe/Tallinn 
                                                        but Was Identified As {2}", latitude, longitude, timeZoneId);
}
```

The output is:
59.470977, 24.708448 Is Europe/Tallinn but Was Identified As **Etc/GMT-2**

And GMT-2 is ambiguous so using e.g. `NodaTimeZoner.IanaToWindows("Etc/GMT-2")` returns South Africa Standard Time instead of the correct FLE Standard Time. I.e. it places these coordinates on a completetly different continent. 

I'm guessing the result is something to do with nautical time zones (https://github.com/mj1856/GeoTimeZone/issues/6) or territorial waters (https://github.com/mj1856/GeoTimeZone/issues/8), but don't really understand the concepts to dig further. 

However, the coordinates under test are actually on land:
https://www.freemaptools.com/radius-around-point.htm?clat=59.4709767&clng=24.7084479&r=0.1&lc=FFFFFF&lw=1&fc=00FF00

And less than 8km driving from centre of Tallinn according to Google Maps (less than 12 nautical miles)? 

Or is the underlying shape data inaccurate (excluding parts of this coastal capital)? 

In any case, the result is wrong:
- is it possible to fix it properly? 
- if not, are there any workarounds I could employ? It's pretty bad to miss by 15000km (from Estonia to South Africa) 
- For instance, do I understand correctly that anything starting with Etc is located in the waters, so as a hack I could ignore all results starting with Etc?

**Comment by mj1856** [comment]
This is now working properly in version 2.0.0, as we have increased fidelity with the OSM maps.  See #23.

Thanks.
