### ISSUE TITLE
Switch to OSM time zone boundaries

### ISSUE THREAD

**Issue by mj1856** [mj1856/GeoTimeZone#23]
The boundaries created by the [Time Zone Boundary Builder](https://github.com/evansiroky/timezone-boundary-builder) project use Open Street Map (OSM) data, which appear to be more accurate than the tz_world map sources, and include territorial waters, which simply coast lines and address our issue #8.

We should switch to this source.

**Comment by sibartlett** [comment]
Nice find!

**Comment by mj1856** [comment]
This is complete with version 2.0.0.
