### ISSUE TITLE
Getting America/Los_Angeles instead of America/Vancouver near border

### ISSUE THREAD

**Issue by ksangha1** [mj1856/GeoTimeZone#24]
Hi there, I put in a lat/lng of (49.0427211, -122.8466416) which should return "America/Vancouver" but fails to do that, and return Etc/GMT+8 where the offset is wrong, should be -8, I tried debugging through the TimeZoneLookup call and narrowed it down to  
line 14 in class TimeZoneLookup: var lineNumber = GetTzDataLineNumbers(geohash); Hoping you can clarify what's happening there. Thanks 

Karn

**Comment by sibartlett** [comment]
We are planning to switch to a more accurate data source which may resolve this issue.

However, the fallback timezone offset is correct - as IANA timezones are "reversed".

`Etc/GMT+8` uses the abbreviation "GMT+8" and corresponds to 8 hours behind UTC (i.e. west of Greenwich) - even though many people would expect it to mean 8 hours ahead of UTC (i.e. east of Greenwich).

**Comment by ksangha1** [comment]
Thanks for the quick clarification with the offset, I used a lat, lng that was a little off from the previous one and that returned the right IANA timezone. Maybe it's just those particular coordinates?

**Comment by mj1856** [comment]
With the new data source (see #23), this now returns `America/Los_Angeles`.

Checking the map, it is indeed within the defined border for `America/Vancouver`, but it is only 4.5km North of the border.

We encode at GeoHash level 5, which [wikipedia says](https://en.wikipedia.org/wiki/Geohash) should be +/- 2.4km margin of error.

If I go a tiny bit further north, it get's it fine.  So I'm not sure if there's something we can do here or not.  Keeping open for now.  

@sibartlett - any thoughts?

**Comment by mj1856** [comment]
Note that `America/Vancouver` *does* show up in the `AlternativeResults` list, so perhaps this is just what we expected with the commentary in #10?

**Comment by mattjohnsonpint** [comment]
Please provide feedback on the precision issue here: #56
Thanks!
