### ISSUE TITLE
Referenced Assembly xxx does not have strong name

### ISSUE THREAD

**Issue by Sigurdur42** [mj1856/GeoTimeZone#25]
Hi,
Can you please sign the assembly with some generated key? I cannot use the nuget package right now because the assembly is not signed.
Thx
Michael

**Comment by mj1856** [comment]
Sorry, but this is an old debate, and I'd rather not.

If you must use it in a project that is strong-named, then use a tool like [https://github.com/brutaldev/StrongNameSigner](StrongNameSigner) or [Nivot.StrongNaming](https://github.com/oising/strongnaming)

**Comment by isctays** [comment]
hi, i created a fork to make a strong named version. still not published but i would like to have your OK @mj1856

**Comment by mj1856** [comment]
I think (you did publish it already)(https://www.nuget.org/packages/GeoTimeZone.StrongNamed/).

If this makes your experience better, then fine - but I'm still not sure why it is important.  See FAQ 1 [here](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md).

Also, others that have done this in the past [have been bad about staying up to date](https://www.nuget.org/packages?q=timezoneconverter), so please do.
