### ISSUE TITLE
Rename Asia/Rangoon TZ to Asia/Yangon

### ISSUE THREAD

**Issue by acidshards** [mj1856/GeoTimeZone#28]
The Asia/Rangoon TZ has been renamed to Asia/Yangon (see [ftp://ftp.iana.org/tz/tzdb/asia](url) for further details) but TZL.dat still references Asia/Rangoon.

**Comment by mj1856** [comment]
This is in our source data for the time zone boundaries.  Link above.

I'll leave this open to remind me to publish a new release when they've updated.

Thanks.

**Comment by mj1856** [comment]
Done in version 3.1.0.
