### ISSUE TITLE
Possible to improve accuracy?

### ISSUE THREAD

**Issue by moab360** [mj1856/GeoTimeZone#30]
Hi there, I'm hoping to use this project but I was noticing inaccurate timezone borders.  Out of curiosity I visualized what GeoTimeZone was producing onto google maps.  Here is an example of Indiana which does a good job showing issues with the east/west side of the state as well as the southern portion where there are a set of timezones separated by rivers

![image](https://user-images.githubusercontent.com/15697848/33357320-4ef770e2-d476-11e7-8766-78a13e6872c9.png)

This is a little too far off for me to use in the current state so I was wondering is there a way to compile this project so that time zones are more accurate?  Perf isn't too big of a concern.

Thanks!

**Comment by mj1856** [comment]
We're currently using a geohash depth of 5, which offers a worst case precision of ~4.9km (at the equator).  There are other algorithms, and of course you could use a deeper depth.  Some of this is talked about in #10 already.

We currently don't have an easy way to build data at a variable depth setting.  The 5 is scattered about in a few hardcoded places.  It should probably be brought to the top as an input parameter.  I'd be glad for a PR to do that, if you are so inclined.  :wink:

**Comment by mj1856** [comment]
Also, I'm curious what tool/code you used to build the map image you posted?

**Comment by mj1856** [comment]
Another approach would be to just take the raw [tz boundary map](https://github.com/evansiroky/timezone-boundary-builder) shapefile and do a point-in-polygon at runtime.  That's a heavier/slower solution, but it would be more accurate than indexing.

**Comment by moab360** [comment]
Cool, thanks for the info.  The code I used to generate the map was pulled out of a larger project I've got which generates map tiles for weather models.  I simply plugged GeoTimeZone into the main loop.  Unfortunately not in a shareable state though.

I'll look into making a variable geohash depth and see if I can get it working.

**Comment by mattjohnsonpint** [comment]
Please provide feedback on the precision issue here: #56
Thanks!
