### ISSUE TITLE
Change Asia/Kolkata to Asia/Calcutta

### ISSUE THREAD

**Issue by Pascal1988M** [mj1856/GeoTimeZone#32]
Asia/Kolkata is not a valid timezone. It should be Asia/Calcutta instead.

**Comment by jnyrup** [comment]
According to IANA `Asia/Kolkata` is the official time zone identifier.
In the latest [release](https://data.iana.org/time-zones/releases/tzdata2018e.tar.gz)
`zone.tab` contains `Asia/Kolkata` but not `Asia/Calcutta`.
In the same archive, the file `backward` lists `Asia/Calcutta` as an alias for `Asia/Kolkata`.

For historical description see https://en.wikipedia.org/wiki/Time_in_India

**Comment by mj1856** [comment]
They are both valid time zones identifiers.  The current canonical `Zone` entry is `Asia/Kolkata`, which should be what this library returns.  `Asia/Calcutta` is a `Link` entry, pointing back as `Asia/Kolkata`.

The change was made back in tzdb 2012e [with this commit](https://github.com/eggert/tz/commit/fcab3a4859f2876c7735708fcf1a8524b61f5bc7).

If you are finding it to be invalid in your environment, then you are using a release older that 2012e, and should update to the current data.
