### ISSUE TITLE
How to get the timezone in number?

### ISSUE THREAD

**Issue by jrahma** [mj1856/GeoTimeZone#33]
Hi,

How can I get the timezone in numbers, for example +3, -4, etc?

Thanks,
Jassim

**Comment by jnyrup** [comment]
GeoTimeZone cannot answer that question.

As stated on the front page its purpose is:
> Provides an IANA time zone identifier from latitude and longitude coordinates.

If you are not aware of the difference between a time zone and a time zone *offset*, I can recommend this [blog post](https://codeofmatt.com/2015/02/07/what-is-a-time-zone/).

To solve your problem, you can e.g. use [NodaTime](https://github.com/nodatime/nodatime).

E.g.

```csharp
DateTimeZone TimeZone = DateTimeZoneProviders.Tzdb["America/Chicago"];
TimeSpan offset = TimeZone.GetUtcOffset(SystemClock.Instance.GetCurrentInstant()).ToTimeSpan();
```

**Comment by mj1856** [comment]
Yes, exactly.  Thanks.
