### ISSUE TITLE
Getting Europe/Moscow instead Europe/Tallinn

### ISSUE THREAD

**Issue by Pascal1988M** [mj1856/GeoTimeZone#34]
By using TimeZoneLookup.GetTimeZone(59.37, 28.19).Result
I getting Europe/Moscow it should be Europe/Tallinn

**Comment by mj1856** [comment]
That location is approximately 1km from the border between these two time zones.  We encode with GeoHash level 5, which has a +/- 2.4km margin of error.  You'll find that `Europe/Tallinn` is indeed in the `.AlternativeResults` list.

Essentially, this is a dup of #24, just for a different border.

Thanks.

**Comment by mattjohnsonpint** [comment]
Please provide feedback on the precision issue here: #56
Thanks!
