### ISSUE TITLE
Compress data

### ISSUE THREAD

**Issue by jnyrup** [mj1856/GeoTimeZone#36]
Have you considered compressing `TZ.dat` just as with `data.json.gz` in TimeZoneNames?

As I read the code the additional decompressing would be a one-time penalty when reading `TZ.dat`.

My raw test of gzipping `TZ.dat` shows that would be reduced from 9.82 mb to 1.56 mb.

**Comment by mj1856** [comment]
Completed with version 4.0.0.  Thanks.
