### ISSUE TITLE
How about .Net Time zone standard?

### ISSUE THREAD

**Issue by djnaumov** [mj1856/GeoTimeZone#37]
Can I get .Net standard id of time zone?
For example: TimeZoneLookup.GetTimeZone(50.026034, 36.224942).Result
actual result: "Europe/Kiev"
expected result: "FLE Standard Time"

https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/default-time-zones

**Comment by mj1856** [comment]
FYI - Those are Windows legacy identifiers, not any particular standard.  If you need them, use my [TimeZoneConverter](https://github.com/mj1856/TimeZoneConverter) package.

```csharp
string tzName = TimeZoneLookup.GetTimeZone(50.026034, 36.224942).Result;
string windowsTimeZoneId = TZConvert.IanaToWindows(tzName);
```

Or, if you're just wanting to get to a `TimeZoneInfo` object, then:

```csharp
string tzName = TimeZoneLookup.GetTimeZone(50.026034, 36.224942).Result;
TimeZoneInfo tzi = TZConvert.GetTimeZoneInfo(tzName);
```

**Comment by djnaumov** [comment]
@mj1856, Thank you so much!
