### ISSUE TITLE
GeoTimeZone and Powershell

### ISSUE THREAD

**Issue by eliassal** [mj1856/GeoTimeZone#38]
Hi, can I use GeoTimeZone inside powershell script? if yes can yu please let me know how?
Thanks

**Comment by mj1856** [comment]
In theory, you should be able to author a Powershell Cmdlet and import GeoTimeZone (or any Nuget package) in the process.  You'd then be able to register and use that Cmdlet wherever you wanted.

This is beyond the scope of what I'm providing with this package, but perhaps this will help you get started:
https://docs.microsoft.com/en-us/powershell/developer/cmdlet/writing-a-windows-powershell-cmdlet
