### ISSUE TITLE
Return Windows Time Zone IDs

### ISSUE THREAD

**Issue by lordofscripts** [mj1856/GeoTimeZone#40]
This library returns IANA identifiers which I soon found out via a _TimeZoneNotFoundException_ that they are not useful in Windows. If I could get the actual UTC offset and whether there is DST or not, then it would be useful.

In order to get this to work I had to plug the **TimeZoneConverter** **_NuGet_** to convert these IANA codes from here into something I could use in Windows to get the UTC time offsets and convert dates.

It would be nice if this library provided the information we are missing.

**Comment by mj1856** [comment]
Well, they are both from me, so I could do that. But is there really any benefit?  You'd still end up with them both in your project.

Also then anyone who didn't care about Windows zones would take the dependency unneccesarily.

Also, one might prefer using IANA identifiers with NodaTime.
