### ISSUE TITLE
getting error while trying to install Microsoft.Bot.Builder.AI.Luis version 4.5.1 

### ISSUE THREAD

**Issue by gouravbeyondBGCM** [mj1856/GeoTimeZone#41]
getting following error while trying to install Microsoft.Bot.Builder.AI.Luis version 4.5.1 

Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Microsoft.Bot.Builder.AI.Luis 4.5.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by mj1856** [comment]
That is not relevant to this project.

**Comment by gouravbeyondBGCM** [comment]
> That is not relevant to this project.

then what is the right project for this , please tag it there I need answer for this .

**Comment by mj1856** [comment]
I have no idea.  What would lead you to believe a problem with a package called `Microsoft.Bot.Builder.AI.Luis` would have anything to do with this project, `GeoTimeZone`?

**Comment by mj1856** [comment]
The nuget package project site for that package points here: https://github.com/Microsoft/botbuilder-dotnet.  Perhaps that is the right location.
