### ISSUE TITLE
 Issue with the installation of the BarcodeLib Library

### ISSUE THREAD

**Issue by enrique1227** [mj1856/GeoTimeZone#43]
my problem is the following: I am installing the BarcodeLib library to generate barcodes, but it gives me the following error:

Package 'BarcodeLib.2.2.5' does not exist in project 'UI' Could not install package 'BarcodeLib 2.2.5'. You are trying to install this package into a project that targets '.NETFramework, Version = v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author. ========== Finished ==========

I rename the folder as indicated here: https://stackoverflow.com/questions/42039069/could-not-install-package-you-are-trying-to-install-this-package-into-a-pr

It is installed correctly, but when I try to call the library, it does not appear, I leave a photo, to make it clearer, I hope you understand me and help me.
![pro](https://user-images.githubusercontent.com/44936932/85154552-9580c600-b225-11ea-9e7a-cef57defbe2c.png)

**Comment by mj1856** [comment]
Hi.  This is the GeoTimeZone project.  BarcodeLib is here:
https://github.com/barnhill/barcodelib/issues
