### ISSUE TITLE
Western arizona returns America/Los_Angeles

### ISSUE THREAD

**Issue by darren-clark** [mj1856/GeoTimeZone#45]
Lat long of 34.15, -114.26, which is Avi Suquilla airport returns Los_angeles rather than Phoenix. 
Phoenix is returned as an alternate, but this location is definately across the border, and an airport, which can be especially problematic.

**Comment by mj1856** [comment]
Dup #10, and several others.

**Comment by mattjohnsonpint** [comment]
Please provide feedback on the precision issue here: #56
Thanks!
