### ISSUE TITLE
Handle time zones in territorial waters

### ISSUE THREAD

**Issue by mj1856** [mj1856/GeoTimeZone#8]
If a point is not found on a land mass, then it must be at sea.  Most of the time, it can be calculated by simple formula.  (see #6)

However, if it is within 12 nautical miles (22.2 km) of land, then it is considered to be in [territorial waters](http://en.wikipedia.org/wiki/Territorial_waters), and thus the time zone is that belonging to the closest land mass.

We need to somehow account for this.  It is particularly important for areas like the Philippines where there are lots of little islands.

Perhaps when building the data file, we could find polygons that have no bordering polygons and simply extend them?  I can envision that resolving overlaps might be difficult.  Is there a way to do this?

**Comment by gregology** [comment]
I've done some geo hacking on the timezone data from http://efele.net/maps/tz/world/ to include territorial waters. It's not perfect because I had to simplify some of the shapes iot process the data. https://github.com/gregology/territorial-timezones

**Comment by mj1856** [comment]
@gregology  - Very interesting, and quite useful!

Are you planning on maintaining these maps as tz_world updates over time?  What might be useful is if you could include whatever scripts or manual processing instructions that are necessary to reproduce the results.  Alternatively, perhaps consider working with the tz_world author to have your work included?

I'm weary of switching to your maps without a plan for continued maintenance, but I do like what you've done there.

**Comment by mj1856** [comment]
The OSM boundaries contain territorial waters, so this is complete with 2.0.0.  :)
